#!/bin/bash

echo "neo_bridge create work dir."
sudo mkdir -p ~/.neoware/log
sudo mkdir -p ~/.neoware/maps
sudo mkdir -p ~/.neoware/bash

sudo cp mapping.sh mapping_kill.sh navigation.sh navigation_kill.sh ~/.neoware/bash/

cd ~/.neoware/bash/
sudo chmod 777 *

echo "install end."
